services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Add your API keys here or use a .env file
      # - OPENAI_API_KEY=your_openai_key
      # - ANTHROPIC_API_KEY=your_anthropic_key
      # - POSTMAN_API_KEY=your_postman_key
      # - OLLAMA_BASE_URL=http://host.docker.internal:11434
    env_file:
      # Docker Compose will read these files in order, with later files overriding earlier ones
      - .env.local  # Local development environment variables (gitignored)
      - .env        # Default environment variables (can be committed to git)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - postman-labs-network

  # Optional: Add other services like databases, caches, etc.
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - postman-labs-network

networks:
  postman-labs-network:
    driver: bridge

# volumes:
#   # Add any persistent volumes here
#   app-data:
