services:
  app:
    image: ghcr.io/arun-gupta/postman-labs:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.local
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - postman-labs-network

  sqlite-mcp-server:
    image: ghcr.io/arun-gupta/sqlite-mcp-server:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - postman-labs-network

networks:
  postman-labs-network:
    driver: bridge

volumes:
  app-data:
    driver: local
